# Add these lines to allow full color support in terminal applications
[colors]
draw_bold_text_with_bright_colors = true

[[colors.indexed_colors]]
color = "#EF9F76"
index = 16

[[colors.indexed_colors]]
color = "#F2D5CF"
index = 17

[colors.bright]
black = "0x585273"
blue = "0x78a8ff"
cyan = "0x63f2f1"
green = "0x7fe9c3"
magenta = "0x7676ff"
red = "0xf02e6e"
white = "0x8a889d"
yellow = "0xf2b482"

[colors.cursor]
cursor = "0xa1efd3"
text = "0x1e1c31"

[colors.dim]
black = "#51576D"
blue = "#8CAAEE"
cyan = "#81C8BE"
green = "#A6D189"
magenta = "#F4B8E4"
red = "#E78284"
white = "#B5BFE2"
yellow = "#E5C890"

[colors.hints.end]
background = "#A5ADCE"
foreground = "#303446"

[colors.hints.start]
background = "#E5C890"
foreground = "#303446"

[colors.normal]
black = "0x1e1c31"
blue = "0x91ddff"
cyan = "0xabf8f7"
green = "0xa1efd3"
magenta = "0xd4bfff"
red = "0xf48fb1"
white = "0xcbe3e7"
yellow = "0xffe6b3"

[colors.primary]
background = "0x1e1c31"
bright_foreground = "0xcbe3e7"
dim_foreground = "0xcbe3e7"
foreground = "0xcbe3e7"

[colors.search.focused_match]
background = "#A6D189"
foreground = "#303446"

[colors.search.matches]
background = "#A5ADCE"
foreground = "#303446"

[colors.selection]
background = "#F2D5CF"
text = "#303446"

[colors.vi_mode_cursor]
cursor = "#BABBF1"
text = "#303446"

[cursor]
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 20

# MonoLisa Helmer Nerd Font
[font.bold]
family = "MonoLisaHelmer Nerd Font"
style = "Bold"

[font.bold_italic]
family = "MonoLisaHelmer Nerd Font"
style = "Bold Italic"

[font.italic]
family = "MonoLisaHelmer Nerd Font"
style = "Regular Italic"

[font.normal]
family = "MonoLisaHelmer Nerd Font"
style = "Regular"

# CaskaydiaCove Nerd font
# [font.bold]
# family = "CaskaydiaCove Nerd Font"
# style = "Bold"
#
# [font.bold_italic]
# family = "CaskaydiaCove Nerd Font"
# style = "Bold Italic"
#
# [font.italic]
# family = "CaskaydiaCove Nerd Font"
# style = "Italic"
#
# [font.normal]
# family = "CaskaydiaCove Nerd Font"
# style = "Regular"


[font.offset]
x = 0
y = 0

[window]
opacity = 0.95
